.TH HEADER 1 "Avril 2013" "theCmaker's manpages 1.0" Commandes
.SH NOM
header \- Créer un fichier header en langage C.
.SH SYNOPSIS
\fBprepro\fP [\fINOM\fP][\fIDESCRIPTIF\fP]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Crée la trame d'un fichier header C, le descriptif passé après le nom sert pour la section ifndef.
On peut ne pas donner de paramètre.
Il est nécessaire de donner le nom en paramètre si on souhaite donner un descriptif en paramètre également.
.PP
ATTENTION : si les fichiers existent, leur contenu est effacé.
Cette commande est d'un usage préliminaire à la programmation.
.SH AUTEUR
Écrit par theCmaker.
.SH "SIGNALER DES BOGUES"
Signaler toute anomalie de header à pierre-loup.pissavy94@orange.fr
ou bien sur <https://github.com/theCmaker/shell/issues>.
