#! /bin/bash

#fonctions

function makeheader ()
{
  read -p "Descriptif du header : " header
  header="`echo $header | tr '[a-z]' '[A-Z]'`_H__"
  header="`echo $header | tr ' ' '_'`"
  echo -e "#ifndef $header\n#define $header\n#endif" > $*
}

#main

if [ $# == '0' ]; then
  read -p "Nom du fichier : " name
else
  name=$1
fi

# Pose éventuelle d'extension
if [ `tail -c 2 <<<$name` != 'c' ]; then
  name=`echo "$name.c"`;
fi

# Ecriture des headers standard
echo -e "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <math.h>"> $name

# Arguments - headers supplémentaires : -l
arg='first' # Curseur 'argument' pour permettre l'inclusion du header éponyme
if [ $# -gt 1 ]; then
  for i in $* ;  do 
  if [ $arg == 'next' ]; then  
    # Pose éventuelle d'extension
    if [ ${i: -2} != '.h' ]; then
      i=`echo "$i.h"`;
    fi;
    if [ ! -f $i ]; then
      echo "Attention, le header $i va être créé !";
      makeheader $i ;
    fi;
    # Ecriture du header supplémentaire
    echo "#include \"$i\" ">> $name; 
  else 
  arg='next';
  fi;
  done;
fi

echo -e "\nint main (int argc, char ** argv)\n{\n\nreturn 0;\n}">> $name